<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit919ab34c08be78561f7a28d7529c47d1
{
    public static $files = array (
        'a0edc8309cc5e1d60e3047b5df6b7052' => __DIR__ . '/..' . '/guzzlehttp/psr7/src/functions_include.php',
        'aaf15a714e044ce28db1d42cd7ed6038' => __DIR__ . '/..' . '/webdevstudios/cmb2/init.php',
    );

    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Psr\\Http\\Message\\' => 17,
        ),
        'I' => 
        array (
            'Intervention\\Image\\' => 19,
        ),
        'G' => 
        array (
            'GuzzleHttp\\Psr7\\' => 16,
        ),
        'C' => 
        array (
            'Countdown\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Psr\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'Intervention\\Image\\' => 
        array (
            0 => __DIR__ . '/..' . '/intervention/image/src/Intervention/Image',
        ),
        'GuzzleHttp\\Psr7\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/psr7/src',
        ),
        'Countdown\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes/gif-generator/app',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit919ab34c08be78561f7a28d7529c47d1::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit919ab34c08be78561f7a28d7529c47d1::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
